[package]
name = "chip8-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
frand = "0.10.1"
rodio = { version = "0.20.1", default-features = false }
sdl2 = "0.37.0"
thiserror = "2.0.12"
